version: '3'

services:
  elasticsearch:
    image: "elasticsearch:${ELK_VERSION}"
    ports:
      - 9200:9200
      - 9300:9300
    container_name: elasticsearch
    hostname: elasticsearch
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health?wait_for_status=yellow"]
      interval: 30s
      timeout: 10s
      retries: 1
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=false
    volumes:
      - ./data:/usr/share/elasticsearch/data
  kibana:
    image: "kibana:${ELK_VERSION}"
    ports:
      - 5601:5601
    container_name: kibana
    hostname: kibana
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
  arkime-capture:
    image: "arkime:${ARKIME_VERSION}-centos7"
    container_name: arkime-capture
    environment:
      - ES_HOST=localhost
      - ES_PORT=9200
      # - ES_USER=elastic
      # - ES_PASSWORD=password
      # set the target network interface you want to listen on
      - ARKIME_INTERFACE=eth0
      - ARKIME_PASSWORD=admin
      - INITALIZEDB=false
      - WIPEDB=false
      - CAPTURE=on
      - VIEWER=off
      - OPTIONS=--host arkime --node arkime
    depends_on:
      - elasticsearch
    tty: true
    privileged: true
    # Arkime need to turn off some network card options, so use host mode to operate it directly
    network_mode: host
    volumes:
      - ./scripts/startarkime.sh:/opt/arkime/bin/startarkime.sh
      - ./raw:/opt/arkime/raw
  arkime-viewer:
    image: "arkime:${ARKIME_VERSION}-centos7"
    container_name: arkime-viewer
    hostname: arkime
    environment:
      # Make this line true on first execution and false every other time
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      # - ES_USER=elastic
      # - ES_PASSWORD=password
      - ARKIME_INTERFACE=eth0
      - ARKIME_PASSWORD=admin
      - INITALIZEDB=false
      - WIPEDB=false
      - CAPTURE=off
      - VIEWER=on
      # - OPTIONS=--debug
    depends_on:
      - elasticsearch
    ports:
      - 8005:8005
    volumes:
      - ./scripts/startarkime.sh:/opt/arkime/bin/startarkime.sh
      - ./raw:/opt/arkime/raw
    restart: always
