version: "3"

services:
  postgres:
    image: postgres:11.4
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_DB: meuse
      POSTGRES_USER: meuse
      POSTGRES_PASSWORD: meuse
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  meuse:
    image: meuse:1.2.0
    container_name: meuse
    hostname: meuse
    environment:
      MEUSE_CONFIGURATION: /app/meuse.yaml
    depends_on:
      - postgres
    ports:
      - "8855:8855"
    volumes:
      - ./meuse.yaml:/app/meuse.yaml
      - ./data:/app/data
    restart: always
